# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(813, 392)
        Dialog.setStyleSheet("#addUserFrame {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"#addUserFrame QLabel {\n"
"    color: #666666;\n"
"}\n"
"\n"
"#addUserFrame QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 5px;\n"
"    text-align: left;\n"
"    width: 200px;\n"
"    height: 30px\n"
"}\n"
"\n"
"#addUserFrame QPushButton {\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"    padding: 5px 10px;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"#addUserFrame QPushButton:pressed {\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"#errorLbl {\n"
"    background-color: #e6f0ff;\n"
"    color: #e60000;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#addUserFrame QComboBox {\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 3px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"    padding: 5px 10px;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"#addUserBtn {\n"
"    background-color: #198754; \n"
"}\n"
"\n"
"#addUserBtn:hover, #addSavingsBtn:pressed {\n"
"    background-color: #00331f;\n"
"}\n"
"\n"
"#resetBtn { \n"
"    background-color: #0d6efd;\n"
"}\n"
"\n"
"#resetBtn:hover, #resetBtn:pressed { \n"
"    background-color: #000099;\n"
"}\n"
"\n"
"\n"
"#cancelBtn {\n"
"    background-color: #dc3545 ;\n"
"}\n"
"\n"
"#cancelBtn:hover, #cancelBtn:hover {\n"
"    background-color: #b30000;\n"
"}\n"
"")
        self.addUserFrame = QtWidgets.QFrame(Dialog)
        self.addUserFrame.setGeometry(QtCore.QRect(0, -1, 16777211, 401))
        self.addUserFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addUserFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addUserFrame.setObjectName("addUserFrame")
        self.label = QtWidgets.QLabel(self.addUserFrame)
        self.label.setGeometry(QtCore.QRect(300, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.errorLbl = QtWidgets.QLabel(self.addUserFrame)
        self.errorLbl.setGeometry(QtCore.QRect(110, 310, 581, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.errorLbl.setFont(font)
        self.errorLbl.setText("")
        self.errorLbl.setWordWrap(False)
        self.errorLbl.setObjectName("errorLbl")
        self.widget = QtWidgets.QWidget(self.addUserFrame)
        self.widget.setGeometry(QtCore.QRect(20, 47, 751, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.surnameTxt = QtWidgets.QLineEdit(self.widget)
        self.surnameTxt.setMinimumSize(QtCore.QSize(150, 30))
        self.surnameTxt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.surnameTxt.setFont(font)
        self.surnameTxt.setClearButtonEnabled(True)
        self.surnameTxt.setObjectName("surnameTxt")
        self.horizontalLayout.addWidget(self.surnameTxt)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.firstnameTxt = QtWidgets.QLineEdit(self.widget)
        self.firstnameTxt.setMinimumSize(QtCore.QSize(150, 30))
        self.firstnameTxt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.firstnameTxt.setFont(font)
        self.firstnameTxt.setClearButtonEnabled(True)
        self.firstnameTxt.setObjectName("firstnameTxt")
        self.horizontalLayout.addWidget(self.firstnameTxt)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.othernameTxt = QtWidgets.QLineEdit(self.widget)
        self.othernameTxt.setMinimumSize(QtCore.QSize(150, 30))
        self.othernameTxt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.othernameTxt.setFont(font)
        self.othernameTxt.setClearButtonEnabled(True)
        self.othernameTxt.setObjectName("othernameTxt")
        self.horizontalLayout.addWidget(self.othernameTxt)
        self.widget1 = QtWidgets.QWidget(self.addUserFrame)
        self.widget1.setGeometry(QtCore.QRect(20, 100, 751, 33))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.userIDTxt = QtWidgets.QLineEdit(self.widget1)
        self.userIDTxt.setMinimumSize(QtCore.QSize(150, 30))
        self.userIDTxt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.userIDTxt.setFont(font)
        self.userIDTxt.setReadOnly(True)
        self.userIDTxt.setObjectName("userIDTxt")
        self.horizontalLayout_2.addWidget(self.userIDTxt)
        self.label_9 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.designationTxt = QtWidgets.QLineEdit(self.widget1)
        self.designationTxt.setMinimumSize(QtCore.QSize(150, 30))
        self.designationTxt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.designationTxt.setFont(font)
        self.designationTxt.setClearButtonEnabled(True)
        self.designationTxt.setObjectName("designationTxt")
        self.horizontalLayout_2.addWidget(self.designationTxt)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.roleCombo = QtWidgets.QComboBox(self.widget1)
        self.roleCombo.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.roleCombo.setFont(font)
        self.roleCombo.setObjectName("roleCombo")
        self.horizontalLayout_2.addWidget(self.roleCombo)
        self.widget2 = QtWidgets.QWidget(self.addUserFrame)
        self.widget2.setGeometry(QtCore.QRect(20, 160, 781, 32))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.usernameLbl = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.usernameLbl.setFont(font)
        self.usernameLbl.setObjectName("usernameLbl")
        self.horizontalLayout_3.addWidget(self.usernameLbl)
        self.usernameTxt = QtWidgets.QLineEdit(self.widget2)
        self.usernameTxt.setMinimumSize(QtCore.QSize(150, 30))
        self.usernameTxt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.usernameTxt.setFont(font)
        self.usernameTxt.setClearButtonEnabled(True)
        self.usernameTxt.setObjectName("usernameTxt")
        self.horizontalLayout_3.addWidget(self.usernameTxt)
        self.label_12 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.passwordTxt = QtWidgets.QLineEdit(self.widget2)
        self.passwordTxt.setMinimumSize(QtCore.QSize(150, 30))
        self.passwordTxt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.passwordTxt.setFont(font)
        self.passwordTxt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordTxt.setClearButtonEnabled(True)
        self.passwordTxt.setObjectName("passwordTxt")
        self.horizontalLayout_3.addWidget(self.passwordTxt)
        self.label_13 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.confirmPasswordTxt = QtWidgets.QLineEdit(self.widget2)
        self.confirmPasswordTxt.setMinimumSize(QtCore.QSize(150, 30))
        self.confirmPasswordTxt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.confirmPasswordTxt.setFont(font)
        self.confirmPasswordTxt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordTxt.setClearButtonEnabled(True)
        self.confirmPasswordTxt.setObjectName("confirmPasswordTxt")
        self.horizontalLayout_3.addWidget(self.confirmPasswordTxt)
        self.widget3 = QtWidgets.QWidget(self.addUserFrame)
        self.widget3.setGeometry(QtCore.QRect(20, 220, 752, 32))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.dateEnrolledTxt = QtWidgets.QLineEdit(self.widget3)
        self.dateEnrolledTxt.setMinimumSize(QtCore.QSize(150, 30))
        self.dateEnrolledTxt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateEnrolledTxt.setFont(font)
        self.dateEnrolledTxt.setReadOnly(True)
        self.dateEnrolledTxt.setObjectName("dateEnrolledTxt")
        self.horizontalLayout_4.addWidget(self.dateEnrolledTxt)
        self.label_14 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.dateUpdatedTxt = QtWidgets.QLineEdit(self.widget3)
        self.dateUpdatedTxt.setMinimumSize(QtCore.QSize(150, 30))
        self.dateUpdatedTxt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateUpdatedTxt.setFont(font)
        self.dateUpdatedTxt.setReadOnly(True)
        self.dateUpdatedTxt.setObjectName("dateUpdatedTxt")
        self.horizontalLayout_4.addWidget(self.dateUpdatedTxt)
        spacerItem = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.widget4 = QtWidgets.QWidget(self.addUserFrame)
        self.widget4.setGeometry(QtCore.QRect(20, 270, 751, 32))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.resetBtn = QtWidgets.QPushButton(self.widget4)
        self.resetBtn.setMinimumSize(QtCore.QSize(0, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/white/corner-up-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetBtn.setIcon(icon)
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout_5.addWidget(self.resetBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.addUserBtn = QtWidgets.QPushButton(self.widget4)
        self.addUserBtn.setMinimumSize(QtCore.QSize(0, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/white/plus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addUserBtn.setIcon(icon1)
        self.addUserBtn.setObjectName("addUserBtn")
        self.horizontalLayout_5.addWidget(self.addUserBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.cancelBtn = QtWidgets.QPushButton(self.widget4)
        self.cancelBtn.setMinimumSize(QtCore.QSize(0, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/white/power.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelBtn.setIcon(icon2)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_5.addWidget(self.cancelBtn)
        spacerItem4 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Add New User"))
        self.label_6.setText(_translate("Dialog", "Surname:"))
        self.label_8.setText(_translate("Dialog", "Firstname:"))
        self.label_10.setText(_translate("Dialog", "Other name:"))
        self.label_11.setText(_translate("Dialog", "User ID:"))
        self.label_9.setText(_translate("Dialog", "Designation:"))
        self.label_7.setText(_translate("Dialog", "Role:"))
        self.usernameLbl.setText(_translate("Dialog", "Username:"))
        self.label_12.setText(_translate("Dialog", "Password:"))
        self.label_13.setText(_translate("Dialog", "Confirm Password:"))
        self.label_15.setText(_translate("Dialog", "Date Enrolled:"))
        self.label_14.setText(_translate("Dialog", "Date Last Updated:"))
        self.resetBtn.setText(_translate("Dialog", "Reset"))
        self.addUserBtn.setText(_translate("Dialog", "Add User"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))
from static import resource_rc
