# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_savings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(647, 261)
        Dialog.setStyleSheet("#addSavingsFrame {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"#addSavingsFrame QPushButton {\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"    padding: 5px 10px;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"#addSavingsFrame QPushButton:pressed {\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"#errorLbl {\n"
"    background-color: #e6f0ff;\n"
"    color: #e60000;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"#addSavingsFrame QDoubleSpinBox{\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 5px;\n"
"    text-align: left;\n"
"    width: 120px;\n"
"    height: 30px\n"
"}\n"
"\n"
"#addSavingsFrame QComboBox {\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 3px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"    padding: 5px 10px;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"#addSavingsBtn {\n"
"    background-color: #198754; \n"
"}\n"
"\n"
"#addSavingsBtn:hover, #addSavingsBtn:pressed {\n"
"    background-color: #00331f;\n"
"}\n"
"\n"
"#resetBtn { \n"
"    background-color: #0d6efd;\n"
"}\n"
"\n"
"#resetBtn:hover, #resetBtn:pressed { \n"
"    background-color: #000099;\n"
"}\n"
"\n"
"\n"
"#cancelBtn {\n"
"    background-color: #dc3545 ;\n"
"}\n"
"\n"
"#cancelBtn:hover, #cancelBtn:hover {\n"
"    background-color: #b30000;\n"
"}\n"
"")
        self.addSavingsFrame = QtWidgets.QFrame(Dialog)
        self.addSavingsFrame.setGeometry(QtCore.QRect(0, -1, 651, 261))
        self.addSavingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addSavingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addSavingsFrame.setObjectName("addSavingsFrame")
        self.label = QtWidgets.QLabel(self.addSavingsFrame)
        self.label.setGeometry(QtCore.QRect(60, 10, 531, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.addSavingsFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 160, 481, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.resetBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.resetBtn.setMinimumSize(QtCore.QSize(0, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/white/corner-up-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetBtn.setIcon(icon)
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout_11.addWidget(self.resetBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.addSavingsBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.addSavingsBtn.setMinimumSize(QtCore.QSize(0, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/white/plus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addSavingsBtn.setIcon(icon1)
        self.addSavingsBtn.setObjectName("addSavingsBtn")
        self.horizontalLayout_11.addWidget(self.addSavingsBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.cancelBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelBtn.setMinimumSize(QtCore.QSize(0, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/white/power.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelBtn.setIcon(icon2)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_11.addWidget(self.cancelBtn)
        self.layoutWidget1 = QtWidgets.QWidget(self.addSavingsFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 50, 528, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(30)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.monthCombo = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.monthCombo.setFont(font)
        self.monthCombo.setObjectName("monthCombo")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.monthCombo.addItem("")
        self.horizontalLayout_7.addWidget(self.monthCombo)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.yearCombo = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.yearCombo.setFont(font)
        self.yearCombo.setObjectName("yearCombo")
        self.horizontalLayout_8.addWidget(self.yearCombo)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(38, 96, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setVerticalSpacing(30)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.savingsTypeCombo = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.savingsTypeCombo.setFont(font)
        self.savingsTypeCombo.setObjectName("savingsTypeCombo")
        self.savingsTypeCombo.addItem("")
        self.savingsTypeCombo.addItem("")
        self.horizontalLayout_9.addWidget(self.savingsTypeCombo)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        spacerItem6 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_2.setMaximum(99999999999.99)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 2, 1, 1)
        self.errorLbl = QtWidgets.QLabel(self.addSavingsFrame)
        self.errorLbl.setGeometry(QtCore.QRect(60, 205, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.errorLbl.setFont(font)
        self.errorLbl.setText("")
        self.errorLbl.setWordWrap(False)
        self.errorLbl.setObjectName("errorLbl")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Add Savings for Ajewole Peter Oluwole"))
        self.resetBtn.setText(_translate("Dialog", "Reset"))
        self.addSavingsBtn.setText(_translate("Dialog", "Add Savings"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))
        self.label_6.setText(_translate("Dialog", "Month:"))
        self.monthCombo.setItemText(0, _translate("Dialog", "January"))
        self.monthCombo.setItemText(1, _translate("Dialog", "February"))
        self.monthCombo.setItemText(2, _translate("Dialog", "March"))
        self.monthCombo.setItemText(3, _translate("Dialog", "April"))
        self.monthCombo.setItemText(4, _translate("Dialog", "May"))
        self.monthCombo.setItemText(5, _translate("Dialog", "June"))
        self.monthCombo.setItemText(6, _translate("Dialog", "July"))
        self.monthCombo.setItemText(7, _translate("Dialog", "August"))
        self.monthCombo.setItemText(8, _translate("Dialog", "September"))
        self.monthCombo.setItemText(9, _translate("Dialog", "October"))
        self.monthCombo.setItemText(10, _translate("Dialog", "November"))
        self.monthCombo.setItemText(11, _translate("Dialog", "December"))
        self.label_7.setText(_translate("Dialog", "Year:"))
        self.label_8.setText(_translate("Dialog", "Savings Type:"))
        self.savingsTypeCombo.setItemText(0, _translate("Dialog", "Monthly Contribution"))
        self.savingsTypeCombo.setItemText(1, _translate("Dialog", "Cash Deposit"))
        self.label_9.setText(_translate("Dialog", "Amount:"))
from static import resource_rc
