# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlertDialog(object):
    def setupUi(self, AlertDialog):
        AlertDialog.setObjectName("AlertDialog")
        AlertDialog.resize(590, 84)
        AlertDialog.setStyleSheet("#OKBtn {\n"
"    background-color: #0d6efd;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"#AlertDialog {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"#messageLbl {\n"
"    color: #00b33c;\n"
"}")
        AlertDialog.setModal(True)
        self.messageLbl = QtWidgets.QLabel(AlertDialog)
        self.messageLbl.setGeometry(QtCore.QRect(30, 9, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.messageLbl.setFont(font)
        self.messageLbl.setText("")
        self.messageLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLbl.setObjectName("messageLbl")
        self.layoutWidget = QtWidgets.QWidget(AlertDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 571, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.OKBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.OKBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.OKBtn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.OKBtn.setObjectName("OKBtn")
        self.horizontalLayout.addWidget(self.OKBtn)
        spacerItem1 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(AlertDialog)
        QtCore.QMetaObject.connectSlotsByName(AlertDialog)

    def retranslateUi(self, AlertDialog):
        _translate = QtCore.QCoreApplication.translate
        AlertDialog.setWindowTitle(_translate("AlertDialog", "Alert"))
        self.OKBtn.setText(_translate("AlertDialog", "OK"))
