# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1136, 668)
        Form.setStyleSheet("/* Add style for title widget */\n"
"\n"
"#titleWidget {\n"
"    border-image: url(:/img/img/banner.png);\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"\n"
"#titleWidget QLabel {\n"
"    color: #ffffff;\n"
"    font-family: \"Stencil\";\n"
"}\n"
"\n"
"#appNameLbl, #portalNameLbl {\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"#titleLabel3 {\n"
"    font-size: 35px;\n"
"}\n"
"\n"
"/* Set style for function widget */\n"
"\n"
"#funcWidget {\n"
"    background-color: #ffffff;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top: 2px solid #343434;\n"
"    border-right: 2px solid #343434;\n"
"    border-bottom: 2px solid #343434;\n"
"}\n"
"\n"
"/* Set style for all QLabel in function widget */\n"
"\n"
"#funcWidget QLabel {\n"
"    color: #505050;\n"
"}\n"
"\n"
"/* Set style for login and register labels in function widget */\n"
"\n"
"#registerLabel, #loginLabel {\n"
"    font-family: \"Viner Hand ITC\";\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"/* Set style for all QLineEdit in function widget */\n"
"\n"
"#funcWidget QLineEdit {\n"
"    border: 1px solid #d9d9d9;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#funcWidget QLineEdit:focus{\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#funcWidget QPushButton{\n"
"    font-size: 12em;\n"
"    border-radius: 5px;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"#funcWidget QPushButton:pressed{\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#loginBtn, #createBtn {\n"
"    background-color: #3554d1;\n"
"}\n"
"\n"
"#loginBtn:hover, #loginBtn:pressed, #createBtn:hover, #createBtn:pressed {\n"
"    background-color: #0000ff;\n"
"}\n"
"\n"
"#exitBtn {\n"
"    background-color: #d10000;\n"
"}\n"
"\n"
"#exitBtn:hover, #exitBtn:pressed {\n"
"    background-color: #910000;\n"
"}\n"
"\n"
"#registerBtn, #backBtn {\n"
"    background-color: #55aa7f\n"
"}\n"
"\n"
"#registerBtn:hover, #registerBtn:pressed, #backBtn:hover, #backtBtn:pressed {\n"
"    background-color: #3aad00;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(65, 598, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.titleWidget = QtWidgets.QWidget(Form)
        self.titleWidget.setMinimumSize(QtCore.QSize(500, 600))
        self.titleWidget.setMaximumSize(QtCore.QSize(500, 600))
        self.titleWidget.setObjectName("titleWidget")
        self.layoutWidget = QtWidgets.QWidget(self.titleWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(9, -1, 492, 608))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(17, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.appLogoLbl = QtWidgets.QLabel(self.layoutWidget)
        self.appLogoLbl.setMinimumSize(QtCore.QSize(200, 200))
        self.appLogoLbl.setMaximumSize(QtCore.QSize(200, 200))
        self.appLogoLbl.setText("")
        self.appLogoLbl.setPixmap(QtGui.QPixmap(":/img/img/logo2.png"))
        self.appLogoLbl.setScaledContents(True)
        self.appLogoLbl.setObjectName("appLogoLbl")
        self.horizontalLayout_3.addWidget(self.appLogoLbl)
        spacerItem3 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.appNameLbl = QtWidgets.QLabel(self.layoutWidget)
        self.appNameLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.appNameLbl.setWordWrap(True)
        self.appNameLbl.setObjectName("appNameLbl")
        self.verticalLayout.addWidget(self.appNameLbl)
        spacerItem4 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.portalNameLbl = QtWidgets.QLabel(self.layoutWidget)
        self.portalNameLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.portalNameLbl.setObjectName("portalNameLbl")
        self.verticalLayout.addWidget(self.portalNameLbl)
        self.gridLayout_3.addLayout(self.verticalLayout, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(17, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.titleWidget)
        self.funcWidget = QtWidgets.QStackedWidget(Form)
        self.funcWidget.setMinimumSize(QtCore.QSize(500, 600))
        self.funcWidget.setMaximumSize(QtCore.QSize(500, 600))
        self.funcWidget.setObjectName("funcWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem6 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 142, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 142, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 2, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(30)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.loginLabel = QtWidgets.QLabel(self.page)
        self.loginLabel.setStyleSheet("#loginLabel {\n"
"    color: #000000;\n"
"}")
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout_5.addWidget(self.loginLabel)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.usernameTxt = QtWidgets.QLineEdit(self.page)
        self.usernameTxt.setMinimumSize(QtCore.QSize(300, 0))
        self.usernameTxt.setClearButtonEnabled(True)
        self.usernameTxt.setObjectName("usernameTxt")
        self.verticalLayout_3.addWidget(self.usernameTxt)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.passwordTxt = QtWidgets.QLineEdit(self.page)
        self.passwordTxt.setMinimumSize(QtCore.QSize(300, 0))
        self.passwordTxt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordTxt.setClearButtonEnabled(True)
        self.passwordTxt.setObjectName("passwordTxt")
        self.verticalLayout_4.addWidget(self.passwordTxt)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exitBtn = QtWidgets.QPushButton(self.page)
        self.exitBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.exitBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/white/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon)
        self.exitBtn.setIconSize(QtCore.QSize(20, 20))
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_2.addWidget(self.exitBtn)
        self.loginBtn = QtWidgets.QPushButton(self.page)
        self.loginBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loginBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/white/log-in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginBtn.setIcon(icon1)
        self.loginBtn.setIconSize(QtCore.QSize(20, 20))
        self.loginBtn.setObjectName("loginBtn")
        self.horizontalLayout_2.addWidget(self.loginBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.funcWidget.addWidget(self.page)
        self.horizontalLayout.addWidget(self.funcWidget)
        spacerItem10 = QtWidgets.QSpacerItem(65, 588, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)

        self.retranslateUi(Form)
        self.funcWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.appNameLbl.setText(_translate("Form", "FOPAJ FARMERS COOPERATIVE MULTIPURPOSE SOCIETY"))
        self.portalNameLbl.setText(_translate("Form", "MANAGEMENT SYSTEM"))
        self.loginLabel.setText(_translate("Form", "Login"))
        self.label_2.setText(_translate("Form", "Username"))
        self.label_3.setText(_translate("Form", "Password"))
        self.exitBtn.setText(_translate("Form", "Exit"))
        self.loginBtn.setText(_translate("Form", "Login"))
from static import resource_rc
